--- 
:edit_signature: false
:accounts: 
  :default: 
    :email: jason.dusek@gmail.com
    :alternates: []

    :name: Jason Dusek
    :sendmail: /usr/sbin/sendmail -oem -ti
    :signature: /Users/jsn/.signature
:discard_snippets_from_encrypted_messages: false
:ask_for_cc: true
:default_attachment_save_dir: ""
:ask_for_bcc: false
:ask_for_subject: true
:confirm_no_attachments: true
:thread_by_subject: false
:confirm_top_posting: true
:editor: /usr/bin/vim + -f -c 'setlocal spell spelllang=en_us' -c 'set filetype=mail'

