#!/usr/bin/env bash
##
##  So many years of fooling around...
##
##


[ -e $f ] && rm -rf $HISTFILE
#[ -f /etc/profile ] && source /etc/profile


bc="bash_completion"

function bsd_aliases {
  bc="/usr/local/etc/${bc}"
}

function gnu_aliases {
  bc="/etc/${bc}"
}

function dynamic_aliases {
  if sed --version >/dev/null 2>&1
  then  # GNU sed
    regsed="sed -r"
  else  # BSD sed
    regsed="sed -E"
  fi
  if ls --version >/dev/null 2>&1
  then  # GNU ls
    alias l='ls --color'
    alias ll='ls -lA --color'
  else  # BSD ls
    alias l='ls -G'
    alias ll='ls -GlA'
  fi
}

case `uname` in
  FreeBSD)
    bsd_aliases
    dynamic_aliases
    umask 007
    ;;
  Darwin)
    bsd_aliases
    dynamic_aliases
    umask 007
    ;;
  Linux)
    gnu_aliases
    dynamic_aliases
    umask 007
    ;;
esac    

for f in $bc
do
  [ -f $f ] && source $f
done


alias   go='pushd'
alias   b='popd'
alias   h='history'
alias   r='rm -r'
alias   c='clear'
alias   t='tail -n 50'
alias   g='egrep --color'
alias   :x='exit'
alias   :q='exit'
alias   ri='ri -f ansi'


set -o vi


## begin prompt of power ##############################################
# I used to have the prompt set up as a bunch of functions; but that
# didn't work very well with sh. Now, I have mastered the various
# levels of evaluation and quoting of the shell and can confidently
# write hideous macros!

DARK="\[\e[01;34m\]"
NORM="\[\e[01;32m\]"
FADE="\[\e[01;30m\]"
REST="\[\e[00;00m\]"
HIGH="\[\e[01;33m\]"

dir="pwd -P | awk '{ printf \"%-65.65s\", \$0 }'"
sub="$regsed 's/^/$NORM/ ; s|/|$FADE&$NORM|g ; s/:/$DARK&$NORM/g'"
t="date +%H:%M"
hist="history 1 | xargs echo '' | awk '{ printf \"%03.3d\", \$1 + 1 }'"
warn="[ $USER = root ] && echo -n '$HIGH' || echo -n '$FADE'"
bang="echo -ne '\x21'"  ## this gives me a single '!' in bash and sh

prompt=" $DARK: \`$dir | $sub\` \`$warn;$bang;\`$NORM\`$hist\` \`$t | $sub\`
 $DARK:\`$warn\`; $REST"

prepend=''
if [ "${TERM}" = "xterm" ]
then
  my_tty=`tty | awk -F/ '{ print $3 $4}'`
  xterm_title="\[\e]0;${my_tty} \u@\H\007\]"
  prepend="${xterm_title}"
fi

export  PS1="${prepend}${prompt}"
export  PS2='  '

## end prompt of power ################################################


if which vimpager >/dev/null 2>&1
then
  export  PAGER=vimpager
  export  MANPAGER=vimmanpager
fi
export  EDITOR=vim
export  TEXEDIT="${EDITOR} +%d %s"
export  RUBYOPT="${RUBYOPT} -Ku"
export  BROWSER=firefox
export  HISTIGNORE="&:h:exit"
export  PATH=$PATH:/sbin/:/usr/sbin/:$HOME/bin:./bin:.
export  TZ=/usr/share/zoneinfo/America/Los_Angeles

