#!/usr/bin/env bash
##
##  So many years of fooling around...
##
##


[ -e $f ] && rm -rf $HISTFILE


function dynamic_aliases {
  if sed --version >&/dev/null
  then  # GNU sed
    regsed="sed -r"
  else  # BSD sed
    regsed="sed -E"
  fi
  if ls --version >&/dev/null
  then  # GNU ls
    alias l='ls --color'
    alias ll='ls -lA --color'
  else  # BSD ls
    alias l='ls -G'
    alias ll='ls -GlA'
  fi
}

dynamic_aliases

for d in /etc /usr/local/etc /opt/local/etc
do
  [ -f $d/bash_completion ] && source $d/bash_completion
done



## begin prompt of power ##############################################
# I used to have the prompt set up as a bunch of functions; but that
# didn't work very well with sh. Now, I have mastered the various
# levels of evaluation and quoting of the shell and can confidently
# write hideous macros!
#
# At one time, this was supposed to work in Bourne shell, too -- but never
# mind all that.
#

DARK="\[\e[01;34m\]"
NORM="\[\e[01;32m\]"
FADE="\[\e[01;30m\]"
REST="\[\e[00;00m\]"
HIGH="\[\e[01;33m\]"

d="pwd -P | $regsed 's/(.{30})..+..(.{30})/\1....\2/'"
j="awk '{ printf \"%-65.65s\", \$0 }'"
sub="$regsed 's/^/$NORM/ ; s|/|$FADE&$NORM|g ; s/:/$DARK&$NORM/g'"
t="date +%H:%M"
hist="awk '{ printf \"%03.3d\", \$1 }' <<< \\#"
warn="[ `whoami` = root ] && echo -n '$HIGH' || echo -n '$FADE'"
bang="echo -ne '\x21'"  ## this gives me a single '!' in bash and sh

prompt=" $DARK: \`$d | $j | $sub\` \`$warn;$bang;\`$NORM\`$hist\` \`$t | $sub\`
 $DARK:\`$warn\`; $REST"

prepend=''
if [ "${TERM}" = "xterm" ]
then
  my_tty=`tty | awk -F/ '{ print $3 $4}'`
  xterm_title="\[\e]0;${my_tty} \u@\H\007\]"
  prepend="${xterm_title}"
fi

export          PS1="${prepend}${prompt}"
export          PS2='  '

## end prompt of power ################################################


##if which vimpager >&/dev/null
##then
##  export        PAGER=vimpager
##  export        MANPAGER=vimmanpager
##fi
export          EDITOR=vim
export          TEXEDIT="${EDITOR} +%d %s"
export          PATH=$PATH:/sbin/:/usr/sbin/:$HOME/bin:./bin:.
export          TZ=/usr/share/zoneinfo/America/Los_Angeles
export          LANG=en_DK.UTF-8
export          LC_ALL=en_DK.UTF-8

alias           go='pushd'
alias           b='popd'
alias           h='history'
alias           r='rm -r'
alias           :x='exit'
alias           :q='exit'
alias           :e=$EDITOR

set -o vi


