#!/usr/bin/env ruby


%w{
irb/completion
pp
wirble
}.each { |lib| require lib rescue nil }


Wirble.init(:init_colors => true)


IRB.conf[:PROMPT][:SPARSE] = {
  :PROMPT_I => "",
  :PROMPT_S => "",
  :PROMPT_C => "",
  :RETURN  =>  " # => %s\n"
}

IRB.conf[:PROMPT_MODE] = :SPARSE
IRB.conf[:AUTO_INDENT] = true
IRB.conf[:EVAL_HISTORY] = 1000 
IRB.conf[:SAVE_HISTORY] = 100


def refresh
  # load local .irbrc files
  load ".irbrc" if File.file? ".irbrc" and Dir.pwd != ENV['HOME']
  # ¡this is a security risk!
end

refresh

