#!/usr/bin/env ruby

%w{
irb/completion
pp
breakpoint
}.each do |lib|
  begin
    require lib
  rescue LoadError => e
    puts e
  end
end

begin
  Wirble.init(:init_colors => true) if require "wirble"
rescue LoadError => e
  puts e
end

IRB.conf[:PROMPT][:SPARSE] = {
  :PROMPT_I => "",
  :PROMPT_S => "",
  :PROMPT_C => "",
  :RETURN  =>  " # => %s\n"
}

IRB.conf[:PROMPT_MODE] = :SPARSE
IRB.conf[:AUTO_INDENT] = true
IRB.conf[:EVAL_HISTORY] = 1000 
IRB.conf[:SAVE_HISTORY] = 100


# load local environment
# ¡this is a security risk!
def refresh
  # load local .irbrc files
  load ".irbrc" if File.file? ".irbrc" and Dir.pwd != ENV['HOME']
  # load local libs 
  Dir.glob("lib/*.rb") {|f| load(f) if File.file?(f) }
end

def ri(arg)
  puts `ri #{arg}`
end

refresh

