set background=dark
set autoindent
set ruler
set showcmd
set incsearch
set foldmethod=indent
set autowriteall
set autoread
set foldminlines=4

set shiftwidth=2
set tabstop=2
set expandtab

" begin freebsd needs these
set backspace=indent,eol,start
syntax on
set hlsearch
" end freebsd needs these

runtime macros/justify.vim

function! MKDHeader(char)
ruby << RUBY
  cb = VIM::Buffer.current
  ln = cb.line_number
  content = cb.line.strip
  underline = content.gsub(/./, VIM.evaluate("a:char")).rjust(78)
  cb[ln] = content.rjust(78)
  unless cb[ln + 1] == underline 
    cb.append(ln, underline)
  end
RUBY
endfunction

nnoremap just :call Justify(78)<CR>

nnoremap mkdh1 :silent! call MKDHeader("=")<CR>
nnoremap mkdh2 :silent! call MKDHeader("-")<CR>

filetype plugin indent on

autocmd FileType text setlocal textwidth=64 wrap

if has("autocmd") && exists("+omnifunc")
	autocmd Filetype *
	\	if &omnifunc == "" |
	\		setlocal omnifunc=syntaxcomplete#Complete |
	\	endif
endif

augroup mkd
  autocmd BufRead *.mkd  set ai formatoptions=tcroqn2 comments=n:>
augroup END



