set background=dark
set autoindent
set ruler
set showcmd
set incsearch
set foldmethod=indent
set autowriteall
set autoread
set foldminlines=4

set shiftwidth=2
set tabstop=2
set expandtab

" begin freebsd needs these
set backspace=indent,eol,start
syntax on
set hlsearch
" end freebsd needs these

runtime macros/justify.vim

function! MKDHeader(char)
  s/\v\s+/ /g
  right 78
  yank
  put
  s/\v(\w)(\s+)(\w)/\1x\3/g
  s/\w/\=a:char/g
endfunction

nnoremap just :call Justify(78)<CR>

nnoremap mkdh :silent! call MKDHeader("=")<CR>
nnoremap mkdhh :silent! call MKDHeader("-")<CR>

filetype plugin indent on

autocmd FileType text setlocal textwidth=64 wrap

if has("autocmd") && exists("+omnifunc")
	autocmd Filetype *
	\	if &omnifunc == "" |
	\		setlocal omnifunc=syntaxcomplete#Complete |
	\	endif
endif

augroup mkd
  autocmd BufRead *.mkd  set ai formatoptions=tcroqn2 comments=n:>
augroup END



